"""DEFINITION
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89
By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
"""
import time

print("Starting Process")
ts = time.time()

LastVal = 0 #n-2
ActVal = 1 # n-1
ValMax = 4000000 # maximumu value
tot = 0
sol= 0
while ActVal < ValMax:
    tot = ActVal + LastVal
    if (tot%2==0):
        sol += tot    
    LastVal = ActVal
    ActVal = tot
    print(ActVal)


ts = time.time() - ts
print("Time Elapsed :",ts,"s")
print("The sum of the even-valued terms under 4 millions ",1000, "is", sol)